/******************************************************************************/
/***          Generated by IBExpert 2012.02.21 30/01/2016 12:27:31          ***/
/******************************************************************************/

SET SQL DIALECT 3;

SET NAMES ISO8859_1;

CREATE DATABASE 'localhost:D:\Projetos\IntegraCSV\Importador\Dados\IB2.GDB'
USER 'SYSDBA' PASSWORD 'masterkey'
PAGE_SIZE 16384
DEFAULT CHARACTER SET ISO8859_1 COLLATION ISO8859_1;



/******************************************************************************/
/***                                 Tables                                 ***/
/******************************************************************************/



CREATE TABLE AUD (
    EMP_CODIGO  VARCHAR(4) NOT NULL,
    ID          INTEGER NOT NULL,
    PROTOCOLO   VARCHAR(10),
    REGISTRO    BLOB SUB_TYPE 0 SEGMENT SIZE 80
);

CREATE TABLE CFG (
    EMP_CODIGO    VARCHAR(4) NOT NULL,
    ID            INTEGER NOT NULL,
    CAMINHOBANCO  VARCHAR(250),
    SERVIDOR      INTEGER,
    USUARIO       VARCHAR(40),
    SENHA         VARCHAR(40)
);

CREATE TABLE DTB (
    VERSAOBANCO  INTEGER,
    VERSAOAPP    INTEGER
);

CREATE TABLE EMP (
    CODIGO          VARCHAR(4) NOT NULL,
    NOME            VARCHAR(50),
    CARTORIOEST     VARCHAR(4),
    CARTORIOCRD     VARCHAR(10),
    CARTORIOCRS     VARCHAR(10),
    SERVICESEST     VARCHAR(4),
    SERVICESCRD     VARCHAR(10),
    SERVICESCRS     VARCHAR(10),
    CPG_EST         VARCHAR(4),
    CPG_CRD         VARCHAR(10),
    CPG_CRS         VARCHAR(10),
    VDR_COB_CODIGO  VARCHAR(4),
    SER_CODIGO      VARCHAR(4),
    VDR_TDC_CODIGO  VARCHAR(3),
    MDS_CODIGO      VARCHAR(2),
    CPG_FRN_CNPJ    VARCHAR(14)
);

CREATE TABLE IMP (
    EMP_CODIGO  VARCHAR(4) NOT NULL,
    ID          INTEGER NOT NULL,
    DATA        DATE
);

CREATE TABLE REG (
    EMP_CODIGO          VARCHAR(4) NOT NULL,
    ID                  INTEGER NOT NULL,
    PROTOCOLO           VARCHAR(50),
    DATACADASTRO        TIMESTAMP,
    DESPACHANTE         DOUBLE PRECISION,
    DISTRIBUIDOR        DOUBLE PRECISION,
    VALORCARTORIO       DOUBLE PRECISION,
    DAJ                 DOUBLE PRECISION,
    VALORTOTALCUSTAS    DOUBLE PRECISION,
    CONVENIO            VARCHAR(50),
    CUSTASFECHADAS      INTEGER,
    VALORXIMENESGESTAO  DOUBLE PRECISION,
    VALORXIMENESAUT     DOUBLE PRECISION,
    VALORXIMENESREC     DOUBLE PRECISION,
    VALORXIMENESOUTROS  DOUBLE PRECISION,
    REPRESENTANTE       VARCHAR(50),
    VALORXIMENES        DOUBLE PRECISION,
    IMP_ID              INTEGER,
    CRE_CODIGO          VARCHAR(11),
    NUMLINHA            INTEGER,
    CPG_CODIGO          VARCHAR(11)
);



/******************************************************************************/
/***                              Primary Keys                              ***/
/******************************************************************************/

ALTER TABLE AUD ADD CONSTRAINT PK_AUD PRIMARY KEY (EMP_CODIGO, ID);
ALTER TABLE CFG ADD CONSTRAINT PK_CFG PRIMARY KEY (EMP_CODIGO, ID);
ALTER TABLE EMP ADD CONSTRAINT PK_EMP PRIMARY KEY (CODIGO);
ALTER TABLE IMP ADD CONSTRAINT PK_IMP PRIMARY KEY (EMP_CODIGO, ID);
ALTER TABLE REG ADD CONSTRAINT PK_REG PRIMARY KEY (EMP_CODIGO, ID);


/******************************************************************************/
/***                              Foreign Keys                              ***/
/******************************************************************************/

ALTER TABLE IMP ADD CONSTRAINT FK_IMP_EMP FOREIGN KEY (EMP_CODIGO) REFERENCES EMP (CODIGO);
ALTER TABLE REG ADD CONSTRAINT FK_REG_EMP FOREIGN KEY (EMP_CODIGO) REFERENCES EMP (CODIGO);
ALTER TABLE REG ADD CONSTRAINT FK_REG_IMP FOREIGN KEY (EMP_CODIGO, IMP_ID) REFERENCES IMP (EMP_CODIGO, ID) ON DELETE CASCADE;